inertial_frame_id: world
waypoints:
  -
    point: [2, 0, 0]
    max_forward_speed: 0.4
    heading: 0
    use_fixed_heading: False
  -
    point: [4, 4, -5]
    max_forward_speed: 0.4
    heading: 0
    use_fixed_heading: False
  -
    point: [2, 0, -5]
    max_forward_speed: 0.4
    heading: 0
    use_fixed_heading: False
  -
    point: [0, 2, -5]
    max_forward_speed: 0.4
    heading: 0
    use_fixed_heading: False
  -
    point: [0, 0, -2]
    max_forward_speed: 0.4
    heading: 0
    use_fixed_heading: False